= Video Recorder
:toc: left

image:https://travis-ci.org/SergeyPirogov/video-recorder-java.svg?branch=master["Build Status", link="https://travis-ci.org/SergeyPirogov/video-recorder-java"]

This library allows easily record video of your UI tests by just putting couple annotations.

Supports popular Java test frameworks: 

* JUnit 
* TestNg
* Spock
* Selenium Grid

== JUnit Rule:

.maven
[source,java]
----
<dependency>
  <groupId>com.automation-remarks</groupId>
  <artifactId>video-recorder-junit</artifactId>
  <version>LATEST</version>
</dependency>
----

.gradle 
[source,java]
----
compile group: 'com.automation-remarks', name: 'video-recorder-junit', version: '1.+'
----

.JUnitVideoTest.class
[source,java]
----
import com.automation.remarks.video.annotations.Video;  
import com.automation.remarks.video.junit.VideoRule;  
import org.junit.Rule;  
import org.junit.Test;

import static junit.framework.Assert.assertTrue;

public class JUnitVideoTest {

    @Rule
    public VideoRule videoRule = new VideoRule();

    @Test
    @Video
    public void shouldFailAndCreateRecordWithTestName() {
        Thread.sleep(5000);
        assert false;
    }

    @Test
    @Video(name = "second_test")
    public void videoShouldHaveNameSecondTest() {
        Thread.sleep(10000);
        assertTrue(false);
    }
}
----

== TestNG:

.maven
[source,java]
----
<dependency>
  <groupId>com.automation-remarks</groupId>
  <artifactId>video-recorder-testng</artifactId>
  <version>LATEST</version>
</dependency>
----

By default recorder will include testng dependency 6.9.9. If you want to place other version of TestNG use this declaration:

.maven
[source,java]
----
<dependency>
   <groupId>com.automation-remarks</groupId>
   <artifactId>video-recorder-testng</artifactId>
   <version>1.0.+</version>
   <exclusions>
      <exclusion>
         <groupId>org.testng</groupId>
         <artifactId>testng</artifactId>
       </exclusion>
    </exclusions>
</dependency>
----

.gradle 
[source,java]
----
compile group: 'com.automation-remarks', name: 'video-recorder-testng', version: '1.+'
----

.TestNgVideoTest.class
[source,java]
----
import com.automation.remarks.video.annotations.Video;  
import com.automation.remarks.video.testng.VideoListener;  
import org.testng.annotations.Listeners;  
import org.testng.annotations.Test;

import static junit.framework.Assert.assertTrue;

@Listeners(VideoListener.class)
public class TestNgVideoTest {

    @Test
    @Video
    public void shouldFailAndCreateRecordWithTestName() {
        Thread.sleep(1000);
        assert false;
    }

    @Test
    @Video(name = "second_test")
    public void videoShouldHaveNameSecondTest(){
        Thread.sleep(1000);
        assertTrue(false);
    }
}
----
== Configuration

You are able to set some configuration parameters for Video Recorder:

[source,java]
----
  VideoRecorder.conf()
                .withVideoFolder("custom_folder")         // Default is ${user.dir}/video.
                .videoEnabled(true)                       // Disabled video globally
                .withVideoSaveMode(VideoSaveMode.ALL)     // Save videos for passed and failed tests
                .withRecorderType(RecorderType.FFMPEG)    // Monte is Default recorder
                .withRecordMode(RecordingMode.ANNOTATED); // Record video only for tests with @Video
----

or with maven

----
 mvn test -Dvideo.folder=custom_folder // default video
          -Dvideo.enabled=false        // default true
          -Dvideo.mode=ALL             // default ANNOTATED
          -Drecorder.type=FFMPEG       // default MONTE
          -Dvideo.save.mode=ALL        // default FAILED_ONLY
          -Dvideo.frame.rate=1         // default 24
----

== Remote Video Recording:

Build remote module:

----
./gradlew remote:jar
----

Run hub:

----
java -jar video-recorder-remote-1.0.jar -role hub -servlets "com.automation.remarks.remote.hub.Video"
----

Run node:

----
java -jar video-recorder-remote-1.0.jar -servlets "com.automation.remarks.remote.node.VideoServlet" -role node -port 5555 -hub "http://localhost:4444/grid/register"
----

=== TestNG + Remote Video recorder

Change listener in your tests to *RemoteVideoListener*:

.TestNgRemoteVideonTest.class
[source,java]
----
import com.automation.remarks.video.annotations.Video;
import com.automation.remarks.video.testng.VideoListener;
import org.testng.annotations.Listeners;
import org.testng.annotations.Test;

import static junit.framework.Assert.assertTrue;

@Listeners(RemoteVideoListener.class)
public class TestNgRemoteVideonTest {

    @Test
    @Video
    public void shouldFailAndCreateRecordWithTestName() {
        Thread.sleep(1000);
        assert false;
    }

    @Test
    @Video(name = "second_test")
    public void videoShouldHaveNameSecondTest(){
        Thread.sleep(1000);
        assertTrue(false);
    }
}
----

=== Recorder logging

You can log recorder events using log4j.

Just need to set DEBUG level fot *package com.automation.remarks.video.recorder*

Log4j settings example: with Console and File appenders.

----
log4j.rootLogger=INFO, CA, FA

#Console Appender
log4j.appender.CA=org.apache.log4j.ConsoleAppender
log4j.appender.CA.layout=org.apache.log4j.PatternLayout
log4j.appender.CA.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n

#File Appender
log4j.appender.FA=org.apache.log4j.FileAppender
log4j.appender.FA.File=ffmpeg.log
log4j.appender.FA.layout=org.apache.log4j.PatternLayout
log4j.appender.FA.layout.ConversionPattern=[%-5p] %d %c - %m%n

# Set the logger level of File Appender to DEBUG
log4j.logger.com.automation.remarks.video.recorder=DEBUG, FA
log4j.additivity.com.automation.remarks.video.recorder=false
----

## License

See https://github.com/SergeyPirogov/video-recorder-java/blob/master/LICENSE.txt/[LICENSE].

more http://automation-remarks.com/remote-recorder/[details] by http://automation-remarks.com/[automation-remarks.com]
